name: Node CI

on:
    push:
        branches:
            - '**'
        tags:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Get code
              uses: paambaati/codeclimate-action@v6.0.0
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                coverageCommand: make test-coverage
                debug: true
